spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_server_with_http_request
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

